const fs = require('fs-extra');
const path = require('path');
const { execSync } = require('child_process');
const chalk = require('chalk');
const { generatePalette, generateColorsFile } = require('./colors');
const { processTemplate, getTemplateFiles, generateReplacements } = require('./templates');

async function generateProject(projectPath, answers) {
  console.log(chalk.blue('Generating project structure...\n'));
  
  // Create project directory
  await fs.ensureDir(projectPath);
  
  // Generate color palette
  const palette = generatePalette(answers.primaryColor);
  
  // Generate replacements
  const replacements = generateReplacements(answers, palette);
  
  // Get template directory
  const templateDir = path.join(__dirname, '..', 'templates');
  
  // Process all template files
  const templateFiles = getTemplateFiles(templateDir);
  
  for (const templateFile of templateFiles) {
    const relativePath = path.relative(templateDir, templateFile);
    let outputPath = relativePath.replace(/\.template$/, '');
    
    // Handle .gitkeep files
    if (outputPath.endsWith('.gitkeep')) {
      outputPath = outputPath.replace('.gitkeep', '.gitkeep');
    }
    
    const fullOutputPath = path.join(projectPath, outputPath);
    
    // Ensure directory exists
    await fs.ensureDir(path.dirname(fullOutputPath));
    
    // Process template (skip .gitkeep files)
    if (templateFile.endsWith('.gitkeep.template')) {
      // Just create empty .gitkeep file
      await fs.writeFile(fullOutputPath, '', 'utf8');
    } else {
      const content = processTemplate(templateFile, replacements);
      await fs.writeFile(fullOutputPath, content, 'utf8');
    }
  }
  
  // Generate colors.ts file
  const colorsContent = generateColorsFile(palette);
  const colorsPath = path.join(projectPath, 'src/constants/colors.ts');
  await fs.ensureDir(path.dirname(colorsPath));
  await fs.writeFile(colorsPath, colorsContent, 'utf8');
  
  // Create .gitignore
  const gitignore = `node_modules/
.expo/
.expo-shared/
dist/
npm-debug.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision
*.orig.*
web-build/
.DS_Store
*.pem

# Native builds (generated by expo prebuild)
ios/
android/

# local env files
.env*.local

# typescript
*.tsbuildinfo
`;
  await fs.writeFile(path.join(projectPath, '.gitignore'), gitignore);
  
  // Create placeholder assets
  const assetsDir = path.join(projectPath, 'assets');
  await fs.ensureDir(assetsDir);
  
  // Minimal 1x1 transparent PNG (base64)
  const placeholderPng = Buffer.from(
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    'base64'
  );
  
  // Create all required asset files
  await fs.writeFile(path.join(assetsDir, 'icon.png'), placeholderPng);
  await fs.writeFile(path.join(assetsDir, 'splash.png'), placeholderPng);
  await fs.writeFile(path.join(assetsDir, 'adaptive-icon.png'), placeholderPng);
  await fs.writeFile(path.join(assetsDir, 'favicon.png'), placeholderPng);
  
  console.log(chalk.green('✓ Project structure created'));
  console.log(chalk.yellow('⚠ Replace placeholder images in /assets with your actual icons'));
}

module.exports = { generateProject };

